on: 
  schedule:
      - cron: '10 * * * *'
  push:
    paths:
        - '.github/workflows/lending_history.yml'
        - 'lending_history.py'
        - 'borrow_summary.py'
jobs:
  lending_history:
    runs-on: [ubuntu-latest]
    env:
      FTX_API_KEY: ${{ secrets.FTX_API_KEY }}
      FTX_API_SECRET: ${{ secrets.FTX_API_SECRET }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed
          pipenv install
      - name: Get Lending History
        run: pipenv run lending_history
      - name: Get Borrow Summary
        run: pipenv run borrow_summary
